name: seqkit_split2
description: Split single or paired-end fastq.gz or fasta/fa files
keywords:
  - split
  - fastq
  - fasta
  - seqkit
tools:
  - seqkit:
      description: |
        Cross-platform and ultrafast toolkit for FASTA/Q file manipulation, written by Wei Shen.
      homepage: https://github.com/shenwei356/seqkit
      documentation: https://bioinf.shenwei.me/seqkit/
      doi: 10.1371/journal.pone.0163962
      licence: ["MIT"]
      identifier: biotools:seqkit
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: FastQ files or FastA files
        pattern: "*.{fq.gz/fastq.gz}"
output:
  - reads:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "**/*.gz":
          type: file
          description: Split fastq files
          pattern: "*.{fq.gz/fastq.gz}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@FriederikeHanssen"
  - "@heuermh"
  - "@yumisims"
maintainers:
  - "@FriederikeHanssen"
  - "@heuermh"
  - "@yumisims"
